image: Visual Studio 2017

environment:
  nodejs_version: "8.9.1"
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - node -v

build_script:
  - cd frontend
  - yarn install
  - cd ../controller
  - yarn install
  - cd ../electron
  - yarn install
  - yarn dist:win